main:
	gcc main.c op.c voice.c socket.c smoke.c ds18b20.c sr04.c receive.c tiktok.c face.c oled.c myoled.c living.c bed.c fan.c servo.c sound.c check_face.c ini.c hc01.c -o main -I /usr/include/python3.9/ -l python3.9 -lpthread -lwiringPi

.PHONY: main